name: Javaproject
on: push
jobs: 
 tests:
   runs-on: Ubuntu-latest
   steps:
    - name: Get code
      uses: actions/checkout@v4.1.7
      with:
       repository: sample-java-app
    - name: action-maven
      uses: comchangs/action-maven@v0.4-beta
        
